Interactive Telegram App
danicafine/raspberrypi-houseplants pull request #2
Opened 2022-09-23 10:57 UTC by danicafine

Extended the project to include a producer within a Telegram application that allows me to update plants and plant-sensor mappings from my phone.

2022-09-23 11:15 UTC, krisajenkins commented on avro_helper.py
> +def get_schema(file):
Is this function still used enough to be worth having?

2022-09-23 11:16 UTC, krisajenkins commented on avro_helper.py
> +houseplant_schema = get_schema('./avro/houseplant.avsc')
But if that function is used elsewhere, why is this one call in this file?

2022-09-23 11:20 UTC, krisajenkins commented on houseplant_soil_monitor.py
> +SR_CLIENT = SchemaRegistryClient(SR_CONF)
If you changed `schema.registry.url` to just `url` — which would be legitimate because it's already under the `schema-registry` parent - then you could replace this with just `SR_CONF = CONFIGS['schema-registry']`.

2022-09-23 11:23 UTC, krisajenkins commented on houseplant_soil_monitor.py
> +PRODUCER_CONF['value.serializer'] = READINGS_SERIALIZER
YMMV, but I like to say:

```python
PRODUCER_CONF = CONFIGS['kafka'] | {
  'value.serializer': READINGS_SERIALIZER,
}
```

That'll give you a (shallow) copy with the new field(s) added.

2022-09-23 11:26 UTC, krisajenkins commented on houseplant_soil_monitor.py
> +
Same tip as above, for even more benefit. `|`

2022-09-23 11:28 UTC, krisajenkins commented on houseplant_soil_monitor.py
> +            elif msg is not None:
I'd want:

```python
elif msg.error():
    ...
else:
    sensor_id = ...
```

2022-09-23 11:29 UTC, krisajenkins commented on houseplant_soil_monitor.py
> +    while True:
Not strictly true. This will loop for all eternity, won't it?

2022-09-23 11:30 UTC, krisajenkins commented on houseplant_soil_monitor.py
> +while True:
You never close the consumer cleanly. That means if you kill the script and re-run, you'll often have to wait the the dead-consumer detection to kick in, followed by a rebalance. How about wrapping this in a:

```python
try:
  ...
finally:
    consumer.close()
    procuder.flush()
```

...or something?

2022-09-23 11:32 UTC, krisajenkins commented on houseplant_soil_monitor.py
> +PRODUCER = SerializingProducer(PRODUCER_CONF)
Personally, I would only upper-case constants. Producer and consumer aren't constants (you create them at runtime), and arguably that's true for `*_CONF` and `CONFIGS` too.

2022-09-23 11:34 UTC, krisajenkins commented on houseplant_soil_monitor.py
> +CONSUMER.subscribe([MAPPINGS_TOPIC])
You've only got one place where the consumer is used, so I'd put tempted to put the subscribe in that function. Then it's easier to read the message-handling code and see what kind of messages we're expecting.

2022-09-23 11:37 UTC, krisajenkins commented on telegram_houseplant_bot.py
> +
There's a fair bit of duplication between here and `houseplant_soil_monitor.py`. Time to extract?

2022-09-23 11:38 UTC, krisajenkins commented on telegram_houseplant_bot.py
> +        await update.message.reply_text(
Ooh, the Telegram library is async-aware huh? Nice. 👌

2022-09-23 11:40 UTC, krisajenkins commented on telegram_houseplant_bot.py
> +            "You are you authorized to use this application."
Typo: You are you are you are.

2022-09-23 11:41 UTC, krisajenkins commented on telegram_houseplant_bot.py
> +            "You are you authorized to use this application."
Several other places too.

2022-09-23 11:46 UTC, krisajenkins commented on telegram_houseplant_bot.py
> +    if CONFIGS['telegram']['chat-id'] == update.message.chat_id:
If you were feeling spicy, you could refactor this into something like

```python
  async with chat_session(update.message.chat_id):
    context.user_data ...
    ...
    ...
```

The `async with` hooks would give you what you need to check the chat ID is valid (and return an error if not) each time. Thus factoring out this repeated "check-and-error" code.

2022-09-23 11:47 UTC, krisajenkins commented on telegram_houseplant_bot.py
> +
Code duplication, and same `| {...}` comment as before.

2022-09-23 11:50 UTC, krisajenkins commented on telegram_houseplant_bot.py
> +
I would just:

```python
except Exception as e:
  logger.error("Got exception %s", e)
  raise e
```

ie. Don't swallow the exception then return 1 - instead give the caller the exception back. Often they'll get more useful information from the runtime's default handler. In fact, the only reason I'd catch the unhandlable exception is to get it into the logger.

Also, `"Got exception %s", e` is neater.

2022-09-23 11:51 UTC, krisajenkins commented on telegram_houseplant_bot.py
> +    # 3. send metadata message
I'd _definitelyP factor this out. Let's not create more SR clients than we need to.

2022-09-23 11:51 UTC, krisajenkins commented on telegram_houseplant_bot.py
> +        logger.info('Publishing mapping message for key ' + str(k))
Same `%s` comment as above.

2022-09-23 11:52 UTC, krisajenkins commented on telegram_houseplant_bot.py
> +        producer.produce(MAPPING_TOPIC, key=k, value=value)
You're `str`-ing this twice. Not a huge deal, but unnecessary.

2022-09-23 11:52 UTC, krisajenkins commented on telegram_houseplant_bot.py
> +        producer.flush()
I'd do `finally: flush` myself.

2022-09-23 11:53 UTC, krisajenkins commented on telegram_houseplant_bot.py
> +        f"Fetching houseplant metadata from Kafka..."
No harm, but this `f` isn't doing anything for you. There's no formatting required.

2022-09-23 11:53 UTC, krisajenkins commented on telegram_houseplant_bot.py
> +
Use it or kill it I say.

2022-09-23 11:54 UTC, krisajenkins commented on telegram_houseplant_bot.py
> +
Ah wait, I take that back. the `1` and `0` here aren't exit codes, just return codes. Consider an enum here, instead of magic numbers?

2022-09-23 11:55 UTC, krisajenkins commented on telegram_houseplant_bot.py
> +
I'd consider using enums here, instead of magic numbers.

2022-09-23 11:59 UTC, krisajenkins commented on houseplant_soil_monitor.py
> +CONFIGS_FILE = './configs/configs.yaml'
Real nitpick, but I would say `config` single tends to be the preferred version. (eg. `~/.config`)

2022-09-23 12:01 UTC, krisajenkins commented on houseplant_soil_monitor.py
> +            logger.info("Publishing message: key, value: ({},{})".format(str(plant_id), reading))
I'd be tempted to use `f`-strings here, since you're using them in other places:

```python
  logger.info(f"Publishing message: key, value: ({plant_id},{reading})")
```

(Warning: That can be inefficient in a logger if your values are large, and not always logged. But in this case I think you're fine.)

2022-09-23 12:02 UTC, krisajenkins requested changes
I've left a host of comments. Looks good, but could use some tidying. :-)

2022-09-23 12:14 UTC, danicafine commented on avro_helper.py
> +def get_schema(file):
Hmm, get_schema is used three times in this file.

2022-09-23 12:15 UTC, danicafine commented on avro_helper.py
> +houseplant_schema = get_schema('./avro/houseplant.avsc')
But I use it... thrice. Halp.

2022-09-23 12:17 UTC, danicafine commented on houseplant_soil_monitor.py
> +SR_CLIENT = SchemaRegistryClient(SR_CONF)
Good point!

2022-09-23 12:30 UTC, krisajenkins commented on avro_helper.py
> +    def __init__(self, plant_id, moisture, temperature):
Oh, consider using data classes. They'll take care of your `slots` and `_init__` quite nicely: https://realpython.com/python-data-classes/ plus give you some other code for free.

2022-09-23 12:43 UTC, krisajenkins commented on avro_helper.py
> +def get_schema(file):
Okay, I'm blaming the VSCode plugin for that, because searching for it turned up nothing. :-/

2022-09-24 10:28 UTC, danicafine commented on telegram_houseplant_bot.py
> +    if CONFIGS['telegram']['chat-id'] == update.message.chat_id:
Not quite following this, but I'd love to refactor and remove. Will follow up for a better explanation.

2022-09-24 12:02 UTC, danicafine commented on telegram_houseplant_bot.py
> +
I raised it anyway and addressed in the next function.

2022-09-27 13:41 UTC, krisajenkins reviewed
Looking good. Just a few suggestions...

2022-09-27 13:41 UTC, krisajenkins commented on classes/houseplant.py
> +			)
I believe data classes have an `asdict` method that might save you some code here...

2022-09-27 13:41 UTC, krisajenkins commented on classes/mapping.py
> +			)
Again, `asdict`?

2022-09-27 13:41 UTC, krisajenkins commented on classes/reading.py
> +			temperature = self.temperature
And again.

2022-09-27 13:41 UTC, krisajenkins commented on helpers/clients.py
> +MAPPING_TOPIC  = 'houseplant-sensor-mapping'
These definitions are n the config, and separately here in the code. I'd choose one and stick to it.

2022-09-27 13:41 UTC, krisajenkins commented on helpers/clients.py
> +		)
Seems like you could factor these out into functions that took a class (`Reading/Mapping/Houseplant`) and returned a (de)serializer. They're structurally all doing the same thing.

IIRC, python classes are just objects, so they can be passed like regular arguments. `make_serializer(sr_client(), Houseplant)`.

2022-09-27 13:41 UTC, krisajenkins commented on helpers/clients.py
> +		schema_registry_client = schema_registry_client,
Hmm...why is this one different? All the others are `... = sr_client()`.

2022-09-27 13:41 UTC, krisajenkins commented on houseplant_soil_monitor.py
>  TOUCH_LO = 600
This feels like config.

2022-09-27 13:41 UTC, krisajenkins commented on houseplant_soil_monitor.py
> +                continue
I have to say, I find the `while True...continue` thing confusing. I'd much prefer:

```
msg = consumer.poll(1.0)

while msg is not None:
  ...
  msg = consumer.poll(1.0)
```

It's a shame there's no do-while in python. YMMV, but I find `continue` a bit too close to an unlabelled `goto`.

2022-09-27 13:41 UTC, krisajenkins commented on houseplant_soil_monitor.py
> +            elif msg is not None:
I think you want to check/handle `msg.error()` somehow. If only to raise it.

2022-09-27 13:41 UTC, krisajenkins commented on houseplant_tables_streams.sql
> +EMIT FINAL;
Yay. 🎉

2022-09-28 07:19 UTC, danicafine commented on helpers/clients.py
> +		schema_registry_client = schema_registry_client,
bc I'm only human.

2022-09-28 07:47 UTC, krisajenkins commented on helpers/clients.py
> +		schema_registry_client = schema_registry_client,
Or are you dancer? 💃

2022-09-28 11:23 UTC, closed without merging